name: Build and Deploy AI Engine to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: pac-cafeteria-v1
  GAR_LOCATION: us-central1
  REPOSITORY: cafeteria-repo
  IMAGE: ai-engine
  CLUSTER_NAME: cafeteria-cluster
  CLUSTER_ZONE: us-central1-a

jobs:
  build-push-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GCloud
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      # Set up gcloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      # Connect to the Artifact Registry
      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # Connect to K8s Cluster
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_ZONE }}
      
      # Build the Docker image using Git Commit SHA version tag
      - name: Build Docker image
        run: |-
          docker build \
            --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" \
            .services/ai-engine

      # Push the Docker image to Artifact Registry
      - name: Push Docker image
        run: |-
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"

      # Deploy to GKE
      - name: Deploy to GKE
        run: |-
          kubectl set image deployment/ai-engine ai-engine="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"  
          kubectl rollout status deployment/ai-engine
      
    